"""Retro 1994-style HTML exporter for KeroMDizer conversations."""
from __future__ import annotations
import html
import re
from pathlib import Path

from html_github_exporter import _prose_to_html, _section_to_html


RETRO_CSS = """\
body { background: #008080; color: #ffffff;
       font-family: 'Times New Roman', Times, serif; font-size: 14px; }
h1 { text-align: center; color: #ffff00; text-shadow: 2px 2px #000080; }
h3 { color: #00ffff; }
hr { border: 2px ridge #c0c0c0; }
pre { background: #000080; color: #00ff00; border: 2px inset #c0c0c0;
      font-family: 'Courier New', monospace; padding: 8px; }
code { background: #000080; color: #00ff00; font-family: 'Courier New', monospace; }
a { color: #ffff00; }
.user-header { color: #00ffff; }
.assistant-header { color: #00ff00; }
.blink { animation: blink 1s step-start infinite; }
@keyframes blink { 50% { opacity: 0; } }
"""

TWEMOJI_CDN = 'https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/72x72'

EMOJI_MAP = {
    '👤': ('1f464', 'user'),
    '🤖': ('1f916', 'robot'),
}


def _replace_emoji(text: str) -> str:
    """Replace known emoji with pixel-rendered twemoji images."""
    for emoji, (code, label) in EMOJI_MAP.items():
        img = (f'<img src="{TWEMOJI_CDN}/{code}.png" '
               f'alt="{label}" width="16" height="16" '
               f'style="image-rendering:pixelated;vertical-align:middle">')
        text = text.replace(emoji, img)
    return text


def _md_to_retro_html(md: str) -> str:
    """Convert KeroMDizer markdown output to retro HTML body."""
    sections = re.split(r'\n---\n', md)
    parts = []
    for s in sections:
        html_sec = _section_to_html(s.strip())
        if html_sec:
            # Replace emoji in section HTML
            html_sec = _replace_emoji(html_sec)
            parts.append(html_sec)
    return '\n<hr>\n'.join(parts)


def export_html_retro(md_content: str, output_path: Path) -> None:
    """Write retro 1994-style HTML file from rendered markdown string."""
    body = _md_to_retro_html(md_content)
    m = re.search(r'^# (.+)$', md_content, re.MULTILINE)
    title_text = html.escape(m.group(1)) if m else 'Conversation'
    doc = f'''<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<HTML>
<HEAD>
  <META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=UTF-8">
  <TITLE>{title_text}</TITLE>
  <STYLE TYPE="text/css">{RETRO_CSS}</STYLE>
</HEAD>
<BODY>
<CENTER><H1><SPAN CLASS="blink">&#9733;</SPAN> {title_text} <SPAN CLASS="blink">&#9733;</SPAN></H1></CENTER>
<HR>
{body}
<HR>
<CENTER><FONT SIZE="1" COLOR="#c0c0c0">Generated by KeroMDizer &mdash; Best viewed in Netscape Navigator 3.0</FONT></CENTER>
</BODY>
</HTML>
'''
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(doc, encoding='utf-8')
